version: '3.8' # Usamos una versión reciente de Docker Compose

services:
  eventosdiego: # Tu servicio Node.js existente
    build: . # Construye la imagen desde el Dockerfile actual
    working_dir: /root/
    environment:
      - NODE_ENV=production
    ports:
      - 85:8090
    depends_on:
      - postgres
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - eventos_network_diego


  postgres:
    image: postgis/postgis:17-3.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/restauracion.sql:/docker-entrypoint-initdb.d/restauracion.sql
      - ./scripts/semilla.sql:/docker-entrypoint-initdb.d/semilla.sql
    environment:
      - POSTGRES_USER=darcila
      - POSTGRES_PASSWORD=darcila
      - POSTGRES_DB=eventos
    ports:
      - 5435:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U darcila -d eventos" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
        - eventos_network_diego

  redis:
    image: redis:latest
    ports:
      - 6385:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - eventos_network_diego

volumes:
  postgres-data:
  eventos_diego_redis_data:

networks:
  eventos_network_diego:
    name: eventos_network_diego
