name: Desplegar en Google Compute Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Autenticar en Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Configurar SDK de Google Cloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'compute'

    - name: Verificar contenido del directorio local
      run: |
        pwd
        ls -la

    - name: Copiar archivos a la instancia de GCE
      run: |
        gcloud compute scp --recurse /home/runner/work/gestion-eventos/gestion-eventos diego_arcila@test-senior:/home/diego_arcila/proyectos --zone=us-central1-a
    - name: Ejecutar script de despliegue
      run: |
        gcloud compute ssh diego_arcila@test-senior --zone=us-central1-a --command="cd /home/diego_arcila/proyectos/gestion-eventos && docker-compose down --remove-orphans && docker-compose up -d --build"
