name: Desplegar en Google Compute Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22 ]

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Configurar la versión de Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Autenticar en Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Configurar SDK de Google Cloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'compute'

    - name: Crear archivo .env
      run: |
        echo "DOMAIN=${{ secrets.DOMAIN }}" >> .env
        echo "SERVICE_NAME=${{ secrets.SERVICE_NAME }}" >> .env
        echo "KEY_MAPBOX=${{ secrets.KEY_MAPBOX }}" >> .env
        echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
        echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
        echo "POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }}" >> .env
        echo "KEY_JWT=${{ secrets.KEY_JWT }}" >> .env
        echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
        echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env
        cat .env

    - name: Verificar contenido del directorio local
      run: |
        pwd
        ls -la
        

    - name: Veificar version de Node
      run: |
        node --version

    - name: Instalar dependencias
      run: yarn install

    - name: Forzar actualizar dependencias
      run: yarn upgrade cliui string-width

    - name: Ejecutar pruebas
      run: yarn test

    - name: Copiar archivos a la instancia de GCE
      run: |
        gcloud compute scp --recurse /home/runner/work/gestion-eventos/gestion-eventos diego_arcila@test-senior:/home/diego_arcila/proyectos --zone=us-central1-a
    - name: Ejecutar script de despliegue
      run: |
        gcloud compute ssh diego_arcila@test-senior --zone=us-central1-a --command="cd /home/diego_arcila/proyectos/gestion-eventos && docker-compose down --remove-orphans && docker-compose up -d --build"
